// Shillong + Greater Shillong localities shown in selectors (searchable list).
const LOCALITIES = [
  'Police Bazar',
  'Laitumkhrah',
  'Lachumiere',
  'Laban',
  'Rilbong',
  'Malki',
  'Dhankheti',
  'Mawkhar',
  'Jaiaw',
  'Jail Road',
  'Bara Bazar (Iewduh)',
  'Motphran',
  'Garikhana',
  'Jhalupara',
  'Wahingdoh',
  'Mawprem',
  'Lumparing',
  'Rynjah',
  'Nongrim Hills',
  'Nongthymmai',
  'Nongmynsong',
  'Madanrting',
  'Pynthorumkhrah',
  'Demthring',
  'Lapalang',
  'Mawpat',
  'Umpling',
  'Mawlai',
  'Mawlai Nongkwar',
  'Mawlai Mawiong',
  'Mawroh',
  'Nongkseh',
  'Upper Shillong',
  'Happy Valley',
  'Cleve Colony',
  'Oakland',
  "Kench's Trace",
  'Don Bosco Square',
  'Umsohsun',
  'Lummawbah',
  'Risa Colony',
  'Pasteur',
  'Sunny Hills',
  'Lawmali',
  'Polo',
  'Fire Brigade',
  'Mawblei',
  'Riatsamthiah',
  'Pomlakrai',
  'Nongmensong',
  'Nongpoh Road',
  'Mawlong Haat',
  'Umroi Road',
  'Mawdiangdiang',
  'New Shillong Township',
];

export default LOCALITIES;
