/**
 * Structured Shillong locality data — the geographic backbone for SCHEDULED
 * driver matching (service areas, locality affinity, proximity proxy, adjacency
 * fallback). The instant flow matches on live GPS; the scheduled flow has no live
 * GPS at booking time, so it matches on these localities instead.
 *
 * Each locality has:
 *   id           kebab-case stable id (store THIS on drivers/orders, never the label)
 *   name         display label (matches frontend/constants/localities.js)
 *   aliases      alternate spellings used to normalize free-text input
 *   zone         coarse cluster — drives the adjacency fallback (see ZONE_ADJACENCY)
 *   centroid     [lng, lat] — APPROXIMATE. See the banner below.
 *
 * ⚠️ CENTROIDS ARE HAND-PLACED APPROXIMATIONS, NOT SURVEYED COORDINATES.
 *    They are good enough for a coarse proximity *proxy* and for sanity, but the
 *    proximity scoring term should treat them as low-confidence. Run
 *    `npm run seed:localities` (backend/src/seeds/geocode-localities.js) to
 *    regenerate accurate centroids from Google Geocoding into
 *    `localities.centroids.json`, which this module overlays automatically.
 *    Until CENTROIDS_VERIFIED is true, the scorer down-weights / neutralizes the
 *    proximity-proxy term (see bestFit.js).
 *
 * Adjacency is modelled at the ZONE level (ZONE_ADJACENCY), not per-locality —
 * a maintainable, low-error approximation. `areAdjacent(a, b)` is true when two
 * localities share a zone or sit in neighbouring zones. This powers the
 * "widen to adjacent localities" fallback before escalating to a human.
 */

let VERIFIED_CENTROIDS = {};
try {
  // Generated by seed:localities. Absent on a fresh checkout — that's fine.
  VERIFIED_CENTROIDS = require('./localities.centroids.json');
} catch {
  VERIFIED_CENTROIDS = {};
}

const SHILLONG_CENTER = { lat: 25.5788, lng: 91.8933 };

// zone -> neighbouring zones (symmetric; assert-checked at load).
const ZONE_ADJACENCY = {
  central: ['civil', 'west', 'south-laban', 'east-laitum'],
  civil: ['central', 'east-laitum', 'south-laban'],
  'east-laitum': ['central', 'civil', 'east-rynjah', 'south-laban'],
  'east-rynjah': ['east-laitum', 'far-east'],
  'far-east': ['east-rynjah', 'north-mawlai'],
  west: ['central', 'north-mawlai'],
  'north-mawlai': ['west', 'far-east'],
  'south-laban': ['central', 'civil', 'east-laitum', 'south-hills'],
  'south-hills': ['south-laban'],
};

// id, name, aliases, zone, centroid [lng, lat] (APPROX — see banner).
const RAW = [
  // ---- central ----
  ['police-bazar', 'Police Bazar', ['police bazaar', 'pb'], 'central', [91.8829, 25.5747]],
  ['motphran', 'Motphran', [], 'central', [91.8862, 25.5772]],
  ['garikhana', 'Garikhana', [], 'central', [91.8884, 25.5790]],
  ['jhalupara', 'Jhalupara', [], 'central', [91.8901, 25.5808]],
  ['polo', 'Polo', ['polo ground'], 'central', [91.8930, 25.5836]],
  ['fire-brigade', 'Fire Brigade', [], 'central', [91.8845, 25.5762]],
  ['riatsamthiah', 'Riatsamthiah', [], 'central', [91.8812, 25.5781]],
  ['don-bosco-square', 'Don Bosco Square', ['don bosco'], 'central', [91.8870, 25.5818]],
  ['umsohsun', 'Umsohsun', [], 'central', [91.8852, 25.5800]],
  ['lummawbah', 'Lummawbah', [], 'central', [91.8888, 25.5755]],
  ['jail-road', 'Jail Road', [], 'central', [91.8841, 25.5733]],

  // ---- civil / lachumiere ----
  ['lachumiere', 'Lachumiere', ['lachumiere colony'], 'civil', [91.8901, 25.5688]],
  ['malki', 'Malki', ['malki point'], 'civil', [91.8888, 25.5712]],
  ['dhankheti', 'Dhankheti', [], 'civil', [91.8869, 25.5700]],
  ['pasteur', 'Pasteur', [], 'civil', [91.8920, 25.5675]],
  ['lawmali', 'Lawmali', [], 'civil', [91.8935, 25.5705]],

  // ---- east: laitumkhrah ----
  ['laitumkhrah', 'Laitumkhrah', ['laitumkhrah'], 'east-laitum', [91.9008, 25.5702]],
  ['nongrim-hills', 'Nongrim Hills', ['nongrim'], 'east-laitum', [91.9056, 25.5648]],
  ['lumparing', 'Lumparing', [], 'east-laitum', [91.9080, 25.5700]],
  ['risa-colony', 'Risa Colony', [], 'east-laitum', [91.8990, 25.5735]],

  // ---- east: rynjah ----
  ['rynjah', 'Rynjah', [], 'east-rynjah', [91.9100, 25.5805]],
  ['nongthymmai', 'Nongthymmai', [], 'east-rynjah', [91.9050, 25.5775]],
  ['nongmynsong', 'Nongmynsong', [], 'east-rynjah', [91.9135, 25.5840]],
  ['demthring', 'Demthring', [], 'east-rynjah', [91.9120, 25.5760]],
  ['pomlakrai', 'Pomlakrai', [], 'east-rynjah', [91.9160, 25.5790]],
  ['nongmensong', 'Nongmensong', [], 'east-rynjah', [91.9150, 25.5815]],

  // ---- far east / new township ----
  ['madanrting', 'Madanrting', [], 'far-east', [91.9210, 25.5760]],
  ['pynthorumkhrah', 'Pynthorumkhrah', ['pynthor', 'pynthorumkhrah'], 'far-east', [91.9240, 25.5800]],
  ['lapalang', 'Lapalang', [], 'far-east', [91.9280, 25.5740]],
  ['umpling', 'Umpling', [], 'far-east', [91.9320, 25.5775]],
  ['nongpoh-road', 'Nongpoh Road', [], 'far-east', [91.9360, 25.5850]],
  ['mawdiangdiang', 'Mawdiangdiang', [], 'far-east', [91.9420, 25.5620]],
  ['umroi-road', 'Umroi Road', [], 'far-east', [91.9480, 25.5680]],
  ['new-shillong-township', 'New Shillong Township', ['nst', 'new shillong'], 'far-east', [91.9450, 25.5550]],

  // ---- west: mawkhar / iewduh ----
  ['mawkhar', 'Mawkhar', [], 'west', [91.8745, 25.5825]],
  ['jaiaw', 'Jaiaw', [], 'west', [91.8710, 25.5855]],
  ['mawprem', 'Mawprem', [], 'west', [91.8730, 25.5880]],
  ['wahingdoh', 'Wahingdoh', [], 'west', [91.8775, 25.5848]],
  ['bara-bazar', 'Bara Bazar (Iewduh)', ['iewduh', 'bara bazaar', 'barabazar'], 'west', [91.8788, 25.5800]],
  ['mawlong-haat', 'Mawlong Haat', ['mawlong hat'], 'west', [91.8680, 25.5790]],
  ['mawblei', 'Mawblei', [], 'west', [91.8702, 25.5760]],

  // ---- north: mawlai ----
  ['mawlai', 'Mawlai', [], 'north-mawlai', [91.8650, 25.6005]],
  ['mawlai-nongkwar', 'Mawlai Nongkwar', ['nongkwar'], 'north-mawlai', [91.8612, 25.6040]],
  ['mawlai-mawiong', 'Mawlai Mawiong', ['mawiong'], 'north-mawlai', [91.8700, 25.6075]],
  ['mawroh', 'Mawroh', [], 'north-mawlai', [91.8740, 25.5960]],
  ['nongkseh', 'Nongkseh', [], 'north-mawlai', [91.8800, 25.6020]],
  ['mawpat', 'Mawpat', [], 'north-mawlai', [91.8900, 25.6080]],

  // ---- south: laban ----
  ['laban', 'Laban', [], 'south-laban', [91.8830, 25.5635]],
  ['rilbong', 'Rilbong', [], 'south-laban', [91.8800, 25.5600]],

  // ---- south hills ----
  ['happy-valley', 'Happy Valley', [], 'south-hills', [91.8700, 25.5540]],
  ['upper-shillong', 'Upper Shillong', [], 'south-hills', [91.8560, 25.5360]],
  ['cleve-colony', 'Cleve Colony', ['cleve'], 'south-hills', [91.8760, 25.5560]],
  ['oakland', 'Oakland', [], 'south-hills', [91.8810, 25.5580]],
  ['kenchs-trace', "Kench's Trace", ['kench trace', 'kenchs trace'], 'south-hills', [91.8740, 25.5590]],
  ['sunny-hills', 'Sunny Hills', [], 'south-hills', [91.8820, 25.5615]],
];

// Build the canonical list, overlaying any verified centroids.
const LOCALITIES = RAW
  // de-dupe any accidental id collisions defensively (last wins)
  .filter((row, i, arr) => arr.findIndex((r) => r[0] === row[0]) === i)
  .map(([id, name, aliases, zone, centroid]) => ({
    id,
    name,
    aliases,
    zone,
    centroid: VERIFIED_CENTROIDS[id] || centroid, // [lng, lat]
  }));

// True only once every locality has a generated (surveyed) centroid.
const CENTROIDS_VERIFIED =
  LOCALITIES.length > 0 && LOCALITIES.every((l) => Array.isArray(VERIFIED_CENTROIDS[l.id]));

/* ------------------------------------------------------------------ */
/* Lookups                                                            */
/* ------------------------------------------------------------------ */

const _byId = new Map(LOCALITIES.map((l) => [l.id, l]));

// Normalize a free-text locality string -> canonical locality (or null).
const _normKey = (s) =>
  String(s || '')
    .toLowerCase()
    .replace(/\(.*?\)/g, ' ') // drop parentheticals e.g. "(Iewduh)"
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();

const _byNorm = new Map();
for (const l of LOCALITIES) {
  _byNorm.set(_normKey(l.name), l);
  _byNorm.set(_normKey(l.id), l);
  for (const a of l.aliases) _byNorm.set(_normKey(a), l);
}

/** id -> locality object (or null). */
function byId(id) {
  return _byId.get(String(id)) || null;
}

/** Free-text "Laitumkhrah" / "bara bazaar" / id -> canonical locality (or null). */
function normalizeLocality(text) {
  if (!text) return null;
  return _byNorm.get(_normKey(text)) || null;
}

/** Locality id for an order (normalizes its free-text deliveryAddress.locality). */
function localityIdForText(text) {
  const l = normalizeLocality(text);
  return l ? l.id : null;
}

/**
 * Scan a free-text address for any known locality name/alias and return its id
 * (longest match wins). Recovers a locality from a reverse-geocoded line like
 * "Umpling, Shillong, Meghalaya 793006" when no explicit locality was provided.
 */
function detectFromText(text) {
  if (!text) return null;
  const hay = ` ${_normKey(text)} `;
  let best = null;
  for (const l of LOCALITIES) {
    for (const c of [l.name, ...l.aliases]) {
      const key = _normKey(c);
      if (key && hay.includes(` ${key} `) && (!best || key.length > best.len)) {
        best = { id: l.id, len: key.length };
      }
    }
  }
  return best ? best.id : null;
}

/** [lng, lat] centroid for a locality id (or null). */
function centroidOf(id) {
  const l = byId(id);
  return l ? l.centroid : null;
}

/** { lat, lng } centroid (geo.js convention) for a locality id (or null). */
function centerOf(id) {
  const c = centroidOf(id);
  return c ? { lng: c[0], lat: c[1] } : null;
}

/** True if two locality ids are in the same or neighbouring zones. */
function areAdjacent(idA, idB) {
  const a = byId(idA);
  const b = byId(idB);
  if (!a || !b) return false;
  if (a.zone === b.zone) return true;
  return (ZONE_ADJACENCY[a.zone] || []).includes(b.zone);
}

/** All locality ids adjacent to the given id (same zone + neighbouring zones), excluding itself. */
function adjacentIds(id) {
  const base = byId(id);
  if (!base) return [];
  const zones = new Set([base.zone, ...(ZONE_ADJACENCY[base.zone] || [])]);
  return LOCALITIES.filter((l) => l.id !== id && zones.has(l.zone)).map((l) => l.id);
}

module.exports = {
  LOCALITIES,
  SHILLONG_CENTER,
  ZONE_ADJACENCY,
  CENTROIDS_VERIFIED,
  byId,
  normalizeLocality,
  localityIdForText,
  detectFromText,
  centroidOf,
  centerOf,
  areAdjacent,
  adjacentIds,
};
